name: Run Jest tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Sets up MySQL
        uses: mirromutth/mysql-action@v1.1

      - name: Wait for database
        run: |
          while ! nc -z localhost 3306; do sleep 1; done

      - name: Run Jest tests
        run: npm run test
