name: Run Jest tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
        node-version: ${{ matrix.node-version }}

      - name: Install dependences
        run: npm install

      - name: Run tests
        run: npm run test
